### ISSUE TITLE
Why C++

### ISSUE THREAD

**Issue by AlexVasiluta** [stalecu/kilocli#1]
Wouldn't it be easier to write it in a saner language with better actual support for networking?

**Comment by stalecu** [comment]
For one, this is a non-argument, since I can do the job quite fine with libcurl + nhlomann_json and it's a decent experience. Second, I just put some C++ files, didn't even have the chance to use said libraries, I gave up because of my skill issue regarding Conan. I have migrated to another language and didn't put the changes here. You'll have the chance to see me (ab)use your platform soon 😆
